server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/goods_market_db?serverTimezone=GMT
    username: root
    password: fumushaScarecr0w!
    driver-class-name: com.mysql.cj.jdbc.Driver
##type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/mapper/**/*.xml

